version: 0.2
 
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing serverless CLI
      - npm i -g serverless@2
      - cd notes
      - echo Installing npm dependencies of notes service
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      - serverless deploy --stage dev
artifacts:
  files:
    - jnotes-artifact/**/*
  base-directory: notes
  name: MyProjectArtifacts
cache:
  paths:
    - 'notes/node-modules/**/*'

